#!/usr/bin/env bash
# =============================================================================
#  LAB / EDUCATIONAL — SNI-spoofing tunnel, CLOSED-LOOP reference model.
#  Self-signed lab certificate only. Not trusted by anything outside this lab.
# =============================================================================
#
#  sni-tunnel-lab :: setup_certs.sh
#
#  Generates the self-signed certificate + key the VPS tunnel endpoint uses.
#  Run this on the Linux "VPS". Then copy certs/lab-vps-cert.pem to the Windows
#  client machine so the client can verify the endpoint (optional but tidy).
#
#  The SAN list includes zoom.us on purpose: the client presents SNI=zoom.us,
#  and a matching SAN keeps the handshake clean. This certificate proves
#  nothing about the real zoom.us — it is a throwaway generated by you.
# =============================================================================

set -euo pipefail
cd "$(dirname "$0")"

CERT_DIR="certs"
CERT="$CERT_DIR/lab-vps-cert.pem"
KEY="$CERT_DIR/lab-vps-key.pem"
DAYS=365

mkdir -p "$CERT_DIR"

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl not found. Install it (Debian/Ubuntu: sudo apt install openssl)," >&2
  echo "or generate certs with: python3 vps_tunnel_server.py --autocert" >&2
  exit 1
fi

# The SANs cover the forged SNI, a second zero-rated name, a lab hostname, and
# loopback. Add your VPS LAN IP here too if you want the client to verify the
# name strictly (the client disables hostname checks by default, so it is not
# required):  IP:192.168.1.10
SAN="DNS:zoom.us,DNS:teams.microsoft.com,DNS:lab-vps.local,DNS:localhost,IP:127.0.0.1"

echo "Generating self-signed lab certificate ($DAYS days)..."
openssl req -x509 -newkey rsa:2048 -nodes \
  -keyout "$KEY" -out "$CERT" -days "$DAYS" \
  -subj "/CN=zrlab-vps" \
  -addext "subjectAltName=${SAN}" \
  -addext "basicConstraints=CA:FALSE"

chmod 600 "$KEY"
echo
echo "Created:"
echo "  $CERT"
echo "  $KEY   (mode 600)"
echo
echo "SANs: $SAN"
echo
echo "Next:"
echo "  1. Start the VPS endpoint:   python3 vps_tunnel_server.py --with-origin"
echo "  2. (optional) copy $CERT to the Windows client so it can verify the endpoint:"
echo "         scp $CERT <you>@<windows-ip>:.../sni-tunnel-lab/certs/"
